/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IpamRouteImport } from './routes/ipam'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CmdbRouteImport } from './routes/cmdb'
import { Route as IndexRouteImport } from './routes/index'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IpamRoute = IpamRouteImport.update({
  id: '/ipam',
  path: '/ipam',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CmdbRoute = CmdbRouteImport.update({
  id: '/cmdb',
  path: '/cmdb',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cmdb': typeof CmdbRoute
  '/documents': typeof DocumentsRoute
  '/ipam': typeof IpamRoute
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cmdb': typeof CmdbRoute
  '/documents': typeof DocumentsRoute
  '/ipam': typeof IpamRoute
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cmdb': typeof CmdbRoute
  '/documents': typeof DocumentsRoute
  '/ipam': typeof IpamRoute
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cmdb' | '/documents' | '/ipam' | '/search' | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cmdb' | '/documents' | '/ipam' | '/search' | '/tasks'
  id: '__root__' | '/' | '/cmdb' | '/documents' | '/ipam' | '/search' | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CmdbRoute: typeof CmdbRoute
  DocumentsRoute: typeof DocumentsRoute
  IpamRoute: typeof IpamRoute
  SearchRoute: typeof SearchRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipam': {
      id: '/ipam'
      path: '/ipam'
      fullPath: '/ipam'
      preLoaderRoute: typeof IpamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cmdb': {
      id: '/cmdb'
      path: '/cmdb'
      fullPath: '/cmdb'
      preLoaderRoute: typeof CmdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CmdbRoute: CmdbRoute,
  DocumentsRoute: DocumentsRoute,
  IpamRoute: IpamRoute,
  SearchRoute: SearchRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
