/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServiceCatalogRouteImport } from './routes/service-catalog'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecycleBinRouteImport } from './routes/recycle-bin'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MyRequestsRouteImport } from './routes/my-requests'
import { Route as IpamRouteImport } from './routes/ipam'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CmdbRouteImport } from './routes/cmdb'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets.index'
import { Route as ProtocolsIndexRouteImport } from './routes/protocols.index'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as ServiceCatalogIdRouteImport } from './routes/service-catalog.$id'
import { Route as ProtocolsIdRouteImport } from './routes/protocols.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketSettingsRouteImport } from './routes/admin.ticket-settings'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCatalogRoute = ServiceCatalogRouteImport.update({
  id: '/service-catalog',
  path: '/service-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecycleBinRoute = RecycleBinRouteImport.update({
  id: '/recycle-bin',
  path: '/recycle-bin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRequestsRoute = MyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const IpamRoute = IpamRouteImport.update({
  id: '/ipam',
  path: '/ipam',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CmdbRoute = CmdbRouteImport.update({
  id: '/cmdb',
  path: '/cmdb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TicketsRoute,
} as any)
const ProtocolsIndexRoute = ProtocolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtocolsRoute,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketsRoute,
} as any)
const ServiceCatalogIdRoute = ServiceCatalogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ServiceCatalogRoute,
} as any)
const ProtocolsIdRoute = ProtocolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProtocolsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketSettingsRoute = AdminTicketSettingsRouteImport.update({
  id: '/admin/ticket-settings',
  path: '/admin/ticket-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cmdb': typeof CmdbRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/ipam': typeof IpamRoute
  '/my-requests': typeof MyRequestsRoute
  '/notes': typeof NotesRoute
  '/protocols': typeof ProtocolsRouteWithChildren
  '/recycle-bin': typeof RecycleBinRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/service-catalog': typeof ServiceCatalogRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/trash': typeof TrashRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/ticket-settings': typeof AdminTicketSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/protocols/$id': typeof ProtocolsIdRoute
  '/service-catalog/$id': typeof ServiceCatalogIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/protocols/': typeof ProtocolsIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cmdb': typeof CmdbRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/ipam': typeof IpamRoute
  '/my-requests': typeof MyRequestsRoute
  '/notes': typeof NotesRoute
  '/recycle-bin': typeof RecycleBinRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/service-catalog': typeof ServiceCatalogRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/trash': typeof TrashRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/ticket-settings': typeof AdminTicketSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/protocols/$id': typeof ProtocolsIdRoute
  '/service-catalog/$id': typeof ServiceCatalogIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/protocols': typeof ProtocolsIndexRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cmdb': typeof CmdbRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/ipam': typeof IpamRoute
  '/my-requests': typeof MyRequestsRoute
  '/notes': typeof NotesRoute
  '/protocols': typeof ProtocolsRouteWithChildren
  '/recycle-bin': typeof RecycleBinRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/service-catalog': typeof ServiceCatalogRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/trash': typeof TrashRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/ticket-settings': typeof AdminTicketSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/protocols/$id': typeof ProtocolsIdRoute
  '/service-catalog/$id': typeof ServiceCatalogIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/protocols/': typeof ProtocolsIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/cmdb'
    | '/dashboard'
    | '/documents'
    | '/ipam'
    | '/my-requests'
    | '/notes'
    | '/protocols'
    | '/recycle-bin'
    | '/reports'
    | '/search'
    | '/service-catalog'
    | '/settings'
    | '/tasks'
    | '/tickets'
    | '/trash'
    | '/admin/roles'
    | '/admin/teams'
    | '/admin/ticket-settings'
    | '/admin/users'
    | '/protocols/$id'
    | '/service-catalog/$id'
    | '/tickets/$id'
    | '/protocols/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/cmdb'
    | '/dashboard'
    | '/documents'
    | '/ipam'
    | '/my-requests'
    | '/notes'
    | '/recycle-bin'
    | '/reports'
    | '/search'
    | '/service-catalog'
    | '/settings'
    | '/tasks'
    | '/trash'
    | '/admin/roles'
    | '/admin/teams'
    | '/admin/ticket-settings'
    | '/admin/users'
    | '/protocols/$id'
    | '/service-catalog/$id'
    | '/tickets/$id'
    | '/protocols'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/cmdb'
    | '/dashboard'
    | '/documents'
    | '/ipam'
    | '/my-requests'
    | '/notes'
    | '/protocols'
    | '/recycle-bin'
    | '/reports'
    | '/search'
    | '/service-catalog'
    | '/settings'
    | '/tasks'
    | '/tickets'
    | '/trash'
    | '/admin/roles'
    | '/admin/teams'
    | '/admin/ticket-settings'
    | '/admin/users'
    | '/protocols/$id'
    | '/service-catalog/$id'
    | '/tickets/$id'
    | '/protocols/'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CmdbRoute: typeof CmdbRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  IpamRoute: typeof IpamRoute
  MyRequestsRoute: typeof MyRequestsRoute
  NotesRoute: typeof NotesRoute
  ProtocolsRoute: typeof ProtocolsRouteWithChildren
  RecycleBinRoute: typeof RecycleBinRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  ServiceCatalogRoute: typeof ServiceCatalogRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  TrashRoute: typeof TrashRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminTicketSettingsRoute: typeof AdminTicketSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-catalog': {
      id: '/service-catalog'
      path: '/service-catalog'
      fullPath: '/service-catalog'
      preLoaderRoute: typeof ServiceCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycle-bin': {
      id: '/recycle-bin'
      path: '/recycle-bin'
      fullPath: '/recycle-bin'
      preLoaderRoute: typeof RecycleBinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipam': {
      id: '/ipam'
      path: '/ipam'
      fullPath: '/ipam'
      preLoaderRoute: typeof IpamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cmdb': {
      id: '/cmdb'
      path: '/cmdb'
      fullPath: '/cmdb'
      preLoaderRoute: typeof CmdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/protocols/': {
      id: '/protocols/'
      path: '/'
      fullPath: '/protocols/'
      preLoaderRoute: typeof ProtocolsIndexRouteImport
      parentRoute: typeof ProtocolsRoute
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/service-catalog/$id': {
      id: '/service-catalog/$id'
      path: '/$id'
      fullPath: '/service-catalog/$id'
      preLoaderRoute: typeof ServiceCatalogIdRouteImport
      parentRoute: typeof ServiceCatalogRoute
    }
    '/protocols/$id': {
      id: '/protocols/$id'
      path: '/$id'
      fullPath: '/protocols/$id'
      preLoaderRoute: typeof ProtocolsIdRouteImport
      parentRoute: typeof ProtocolsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ticket-settings': {
      id: '/admin/ticket-settings'
      path: '/admin/ticket-settings'
      fullPath: '/admin/ticket-settings'
      preLoaderRoute: typeof AdminTicketSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtocolsRouteChildren {
  ProtocolsIdRoute: typeof ProtocolsIdRoute
  ProtocolsIndexRoute: typeof ProtocolsIndexRoute
}

const ProtocolsRouteChildren: ProtocolsRouteChildren = {
  ProtocolsIdRoute: ProtocolsIdRoute,
  ProtocolsIndexRoute: ProtocolsIndexRoute,
}

const ProtocolsRouteWithChildren = ProtocolsRoute._addFileChildren(
  ProtocolsRouteChildren,
)

interface ServiceCatalogRouteChildren {
  ServiceCatalogIdRoute: typeof ServiceCatalogIdRoute
}

const ServiceCatalogRouteChildren: ServiceCatalogRouteChildren = {
  ServiceCatalogIdRoute: ServiceCatalogIdRoute,
}

const ServiceCatalogRouteWithChildren = ServiceCatalogRoute._addFileChildren(
  ServiceCatalogRouteChildren,
)

interface TicketsRouteChildren {
  TicketsIdRoute: typeof TicketsIdRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsIdRoute: TicketsIdRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CmdbRoute: CmdbRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  IpamRoute: IpamRoute,
  MyRequestsRoute: MyRequestsRoute,
  NotesRoute: NotesRoute,
  ProtocolsRoute: ProtocolsRouteWithChildren,
  RecycleBinRoute: RecycleBinRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  ServiceCatalogRoute: ServiceCatalogRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TicketsRoute: TicketsRouteWithChildren,
  TrashRoute: TrashRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminTicketSettingsRoute: AdminTicketSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
